[package]
name = "n-bch-rs"
version = "0.0.5"
authors = ["neonphog <neonphog@gmail.com>"]
license = "Apache-2.0"

[lib]
name = "n_bch_rs"
crate-type = ["cdylib"]

[dependencies]
reed-solomon = "=0.2.1"
wasm-bindgen = "=0.2.33"
